create table
    "public"."shipping" ("id" bigint generated by default as identity not null, "method" text not null, "price" smallint not null, "min_days" smallint not null, "max_days" smallint not null, is_default boolean not null default false);

alter table "public"."shipping" enable row level security;

CREATE UNIQUE INDEX shipping_method_key ON public.shipping USING btree (method);

CREATE UNIQUE INDEX shipping_pkey ON public.shipping USING btree (id);

alter table "public"."shipping"
add constraint "shipping_pkey" PRIMARY KEY using index "shipping_pkey";

alter table "public"."shipping"
add constraint "shipping_method_key" UNIQUE using index "shipping_method_key";